apiVersion: v1  
kind: Service  
metadata:  
  name: web-service  
  labels:  
    app: web-service  
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30060
      name: http
  selector:  
    app: web-service  
---  
apiVersion: extensions/v1beta1  
kind: Deployment  
metadata:  
  name: web-service  
spec:  
  replicas: 2  
  template:  
    metadata:  
      labels:  
        app: web-service  
        version: v1  
    spec:  
      containers:  
        - name: hello-app  
          image: 100.67.93.140:8081/docker-local/web-image:1
          imagePullPolicy: IfNotPresent
          ports:  
            - containerPort: 8080